### ISSUE TITLE
Activity Logs

### ISSUE THREAD

**Issue by pranav7** [pranav7/cadet-app#87]
Tech Plan: https://docs.google.com/document/d/1KD8LNkUZKK4vXCrbgnN8Zwi6_hFhJ2WLeAkLTXPkLXI/edit#

## Tasks

- [x] Ship Migrations for `ActivityLog`, `StatusChangedEvent` and `CommentCreatedEvent`: **https://github.com/pranav7/cadet-app/pull/84**
- [x] Record ActivityLog when a Post is updated: **https://github.com/pranav7/cadet-app/pull/86**
- [x] Record ActivityLog when a comment/note is created: **https://github.com/pranav7/cadet-app/pull/90**
- [x] Delete activity log and event, when comment or note is deleted: **#93** 
- [x] ActivityLog API (to return logs for a given post) **#91** ([*Relevant section in doc*](https://docs.google.com/document/d/1KD8LNkUZKK4vXCrbgnN8Zwi6_hFhJ2WLeAkLTXPkLXI/edit#heading=h.6qg3z7ds6pw3))
- [x] Backfill and create ActivityLog for existing comments and posts: **https://github.com/pranav7/cadet-app/pull/98**
- [x] ActivityLog frontend [Admin Dashboard]: **https://github.com/pranav7/cadet-app/pull/92**
- [x] ActivityLog frontend [Public Show Page]: **#92**
- [x] Ship :rocket:
